# this file is *not* meant to cover or endorse the use of GitHub Actions, but rather to
# help make automated releases for this project

name: Unittest Python Package

on: push

permissions:
  contents: read

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Run tests
      run: |
        pip install .[test]
        python create_report_dirs.py
        nose2 --config tests/unittest.cfg
    - name: Create coverage
      run: |
        coverage xml

  upload-coverage:
    needs: test-and-coverage
    runs-on: ubuntu-latest
    steps:
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./reports/coverage/coverage.xml
        flags: unittests
        verbose: true
